name: flutter_news_app_cubit
description: Create a news app with flutter and cubit as state management
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  http: ^1.3.0
  get_it: ^8.0.3
  equatable: ^2.0.7
  flutter_bloc: ^9.0.0
  easy_debounce: ^2.0.3
  url_launcher: ^6.3.1
  flutter_hooks: ^0.20.5
  json_annotation: ^4.9.0
  easy_localization: ^3.0.7+1
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true