name: flutter_news_app_cubit
description: Create a news app with flutter and cubit as state management
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
  get_it: ^8.0.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  easy_debounce: ^2.0.3
  url_launcher: ^6.3.0
  flutter_hooks: ^0.20.5
  json_annotation: ^4.9.0
  easy_localization: ^3.0.7
  cached_network_image: ^3.4.1

dependency_overrides:
  win32: ^5.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  bloc_test: ^9.1.7
  mocktail: ^1.0.4
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true