name: flutter_news_app_cubit
description: Create a news app with flutter and cubit as state management
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.0
  get_it: ^7.6.7
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  easy_debounce: ^2.0.3
  url_launcher: ^6.2.3
  flutter_hooks: ^0.20.4
  json_annotation: ^4.8.1
  easy_localization: ^3.0.3
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  bloc_test: ^9.1.5
  mocktail: ^1.0.3
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true