name: best_architecture_challenge
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  http: ^1.3.0
  equatable: ^2.0.7
  flutter_bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.4

flutter:

  uses-material-design: true