name: flutter_simple_firebase_crud_riverpod
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  get_it: ^7.6.4
  cloud_firestore: ^4.9.1
  firebase_auth: ^4.9.0
  firebase_ui_auth: ^1.8.0
  firebase_ui_oauth_google: ^1.2.11
  firebase_ui_oauth_facebook: ^1.2.11
  firebase_core: ^2.15.1
  firebase_storage: ^11.2.6
  flutter_riverpod: ^2.4.0
  equatable: ^2.0.5
  page_indicator: ^0.4.1
  image_picker: ^1.0.4
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3
  mocktail: ^1.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/