name: flutter_currency_converter
description: Currency converter made in flutter
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  http: ^0.13.5
  sqflite: ^2.2.4+1
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  tuple: ^2.0.1
  flutter_simple_calculator: ^2.2.2
  shared_preferences: ^2.0.17
  easy_localization: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  json_serializable: ^6.6.0
  bloc_test: ^9.1.0


flutter:
  uses-material-design: true
  assets:
    - assets/flags/