name: flutter_currency_converter
description: Currency converter made in flutter
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.20.2
  http: ^1.3.0
  sqflite: ^2.4.2
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  tuple: ^2.0.2
  flutter_simple_calculator: ^2.4.0
  shared_preferences: ^2.5.2
  easy_localization: ^3.0.7+1

dependency_overrides:
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  bloc_test: ^10.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/flags/