name: flutter_currency_converter
description: Currency converter made in flutter
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.1
  http: ^0.13.6
  sqflite: ^2.2.8+2
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  tuple: ^2.0.1
  flutter_simple_calculator: ^2.2.3
  shared_preferences: ^2.1.1
  easy_localization: ^3.0.1

dependency_overrides:
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.4
  json_serializable: ^6.6.2
  bloc_test: ^9.1.1


flutter:
  uses-material-design: true
  assets:
    - assets/flags/