name: flutter_simple_firebase_auth
description: A new Flutter project made with GetX

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  get: ^4.7.2
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  firebase_storage: ^12.4.3
  cloud_firestore: ^5.6.4
  google_sign_in: ^6.2.2
  flutter_facebook_auth: ^7.1.1
  equatable: ^2.0.7
  page_indicator:
    git:
      url: https://github.com/CaiJingLong/flutter_page_indicator.git
      ref: cb6481a9ef55efe059c5cce38023a6c517e183cb
  flutter_hooks: ^0.20.5
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  path: ^1.9.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
