name: flutter_simple_firebase_auth
description: A new Flutter project made with GetX

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.14.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.3.8
  firebase_core: ^1.10.0
  firebase_auth: ^3.2.0
  firebase_storage: ^10.1.0
  cloud_firestore: ^3.1.0
  google_sign_in: ^5.2.1
  flutter_facebook_auth: ^3.5.6

  equatable: ^2.0.3
  page_indicator: ^0.4.1

  flutter_hooks: ^0.18.1
  image_picker: ^0.8.4+4
  cached_network_image: ^3.1.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/
