name: http_unit_test
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.5
  cached_network_image: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.2.0
  json_serializable: ^6.3.1


flutter:
  uses-material-design: true