name: basic_landing_webpage
description: Basic landing webpage
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.3.0
  url_strategy: ^0.3.0
  hooks_riverpod: ^2.5.2
  flutter_hooks: ^0.20.5
  webview_flutter_web: ^0.2.3+2
  webview_flutter: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/screenshots/