name: flutter_simple_firebase_auth
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  path: ^1.8.3
  firebase_core: ^2.12.0
  firebase_auth: ^4.6.0
  firebase_storage: ^11.2.0
  cloud_firestore: ^4.7.0
  google_sign_in: ^6.1.0
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  page_indicator: ^0.4.1
  flutter_facebook_auth: ^5.0.11
  flutter_hooks: ^0.18.6
  image_picker: ^0.8.7+5
  cached_network_image: ^3.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
