name: flutter_simple_firebase_crud_cubit
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  get_it: ^8.0.3
  flutter_bloc: ^9.0.0
  firebase_core: ^3.12.0
  cloud_firestore: ^5.6.4
  firebase_storage: ^12.4.3
  firebase_auth: ^5.5.0
  firebase_ui_auth: ^1.16.1
  firebase_ui_oauth_google: ^1.4.1
  firebase_ui_oauth_facebook: ^1.3.1
  equatable: ^2.0.7
  page_indicator:
    git:
      url: https://github.com/CaiJingLong/flutter_page_indicator.git
      ref: cb6481a9ef55efe059c5cce38023a6c517e183cb
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.4


flutter:
  uses-material-design: true
  assets:
    - assets/