name: flutter_simple_firebase_crud_cubit
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get_it: ^7.2.0
  cloud_firestore: ^3.4.5
  firebase_auth: ^3.6.4
  firebase_core: ^1.21.0
  firebase_storage: ^10.3.6
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  page_indicator: ^0.4.1
  image_picker: ^0.8.5+3
  cached_network_image: ^3.2.1
  flutterfire_ui: ^0.4.3+6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  bloc_test: ^9.1.0
  mocktail: ^0.3.0


flutter:

  uses-material-design: true
  assets:
    - assets/