name: flutter_simple_firebase_crud_cubit
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  get_it: ^7.6.0
  flutter_bloc: ^8.1.2
  firebase_core: ^2.12.0
  cloud_firestore: ^4.7.0
  firebase_storage: ^11.2.0
  firebase_auth: ^4.6.0
  firebase_ui_auth: ^1.4.0
  firebase_ui_oauth_google: ^1.2.0
  firebase_ui_oauth_facebook: ^1.2.0
  equatable: ^2.0.5
  page_indicator: ^0.4.1
  image_picker: ^0.8.7+5
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  bloc_test: ^9.1.1
  mocktail: ^0.3.0


flutter:
  uses-material-design: true
  assets:
    - assets/