// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoLHsnqrIOUbDKaq4DWpbkloknBijhC8Q',
    appId: '1:925019682416:web:e73b03cce1e8e1fd1426b5',
    messagingSenderId: '925019682416',
    projectId: 'address-book-prod',
    authDomain: 'address-book-prod.firebaseapp.com',
    databaseURL: 'https://address-book-prod.firebaseio.com',
    storageBucket: 'address-book-prod.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO95eXGHblC1CHvsZiBof0CEYv9ycx9qg',
    appId: '1:925019682416:android:3de11c045ffa4fd51426b5',
    messagingSenderId: '925019682416',
    projectId: 'address-book-prod',
    databaseURL: 'https://address-book-prod.firebaseio.com',
    storageBucket: 'address-book-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0IwxEC1Z1pc23Zhq91W1gbB0KXwaAurY',
    appId: '1:925019682416:ios:d6367307debd1b5d1426b5',
    messagingSenderId: '925019682416',
    projectId: 'address-book-prod',
    databaseURL: 'https://address-book-prod.firebaseio.com',
    storageBucket: 'address-book-prod.appspot.com',
    androidClientId: '925019682416-u7n63ba76vtdas0fbu81rebja3jmjvoe.apps.googleusercontent.com',
    iosClientId: '925019682416-2s33mbmpcaj9old3dk56cgrt8o8qb973.apps.googleusercontent.com',
    iosBundleId: 'com.nopalsoft.flutterSimpleFirebaseCrudCubit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0IwxEC1Z1pc23Zhq91W1gbB0KXwaAurY',
    appId: '1:925019682416:ios:d6367307debd1b5d1426b5',
    messagingSenderId: '925019682416',
    projectId: 'address-book-prod',
    databaseURL: 'https://address-book-prod.firebaseio.com',
    storageBucket: 'address-book-prod.appspot.com',
    androidClientId: '925019682416-u7n63ba76vtdas0fbu81rebja3jmjvoe.apps.googleusercontent.com',
    iosClientId: '925019682416-2s33mbmpcaj9old3dk56cgrt8o8qb973.apps.googleusercontent.com',
    iosBundleId: 'com.nopalsoft.flutterSimpleFirebaseCrudCubit',
  );
}
