name: flutter_simple_rest_api_getx
description: Learn flutter. Http, Getx, Sqflite, UnitTest
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  get: ^4.7.2
  http: ^1.3.0
  path: ^1.9.1
  shimmer: ^3.0.0
  sqflite: ^2.4.2
  cached_network_image: ^3.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mockito: ^5.4.5
  build_runner: ^2.4.15

flutter:

  uses-material-design: true