name: flutter_connectivity_tutorial
description: Learn how to check if your app has internet connection
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  provider: ^6.0.5
  flutter_bloc: ^8.1.1

  rxdart: ^0.27.7
  connectivity_plus: ^3.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


flutter:
  uses-material-design: true