// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO95eXGHblC1CHvsZiBof0CEYv9ycx9qg',
    appId: '1:925019682416:android:b3326a73acc36cc71426b5',
    messagingSenderId: '925019682416',
    projectId: 'address-book-prod',
    databaseURL: 'https://address-book-prod.firebaseio.com',
    storageBucket: 'address-book-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0IwxEC1Z1pc23Zhq91W1gbB0KXwaAurY',
    appId: '1:925019682416:ios:06d1c778a63981861426b5',
    messagingSenderId: '925019682416',
    projectId: 'address-book-prod',
    databaseURL: 'https://address-book-prod.firebaseio.com',
    storageBucket: 'address-book-prod.appspot.com',
    androidClientId: '925019682416-u7n63ba76vtdas0fbu81rebja3jmjvoe.apps.googleusercontent.com',
    iosClientId: '925019682416-dtf9l208n0o7hv23o59ncgls4a84t4k5.apps.googleusercontent.com',
    iosBundleId: 'com.nopalsoft.flutterSimpleFirebaseCrudGetx',
  );
}
