name: dart_desde_cero_para_principiantes
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.2.6 <4.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.11.1
