name: flutter_bloc_architecture
description: Demonstrate the architecture of the app using flutter bloc
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  get_it: ^7.6.0
  http: ^0.13.6
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  url_launcher: ^6.1.11
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.4
  json_serializable: ^6.6.2
  bloc_test: ^9.1.1
  mockito: ^5.4.0


flutter:
  uses-material-design: true