// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader{
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>> load(String fullPath, Locale locale ) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String,dynamic> zh_CN = {
  "app_name": "Currency Convertor",
  "search_currency": "搜索货币",
  "selected_currency": "（选择货币）",
  "converter": "变流器",
  "favorites": "最爱",
  "change_language": "更改语言",
  "updated_date": "更新时间：{}",
  "updating": "更新中...",
  "main_screen_instructions": "点击货币，使其基础货币。长按要重新排列。",
  "settings": "设置",
  "decimals": "小数点",
  "decimals_description": "小数到显示的号码",
  "grouping_separator": "分组分隔",
  "grouping_separator_description": "启用用于千位分隔符",
  "decimal_separator": "小数分隔符",
  "decimal_separator_description": "符号用于将整数部分从小数部分分离",
  "decimal_comma": "小数逗号",
  "decimal_point": "小数点",
  "currency_symbol": "货币符号",
  "currency_symbol_description": "选择在哪里显示货币符号",
  "currency_symbol_start": "开始",
  "currency_symbol_end": "结束",
  "date_time_format": "yyyy年M月d日 k:mm",
  "key_AED": "阿联酋迪拉姆",
  "key_AFN": "阿富汗阿富汗尼",
  "key_ALL": "阿尔巴尼亚列克",
  "key_AMD": "亚美尼亚德拉姆",
  "key_ANG": "荷兰Antillian荷兰盾",
  "key_AOA": "安哥拉宽扎",
  "key_ARS": "阿根廷比索",
  "key_AUD": "澳大利亚元",
  "key_AWG": "货币编号",
  "key_AZN": "阿塞拜疆马纳特",
  "key_BAM": "波斯尼亚和黑塞哥维那可兑换马克",
  "key_BBD": "巴巴多斯元",
  "key_BDT": "孟加拉塔卡",
  "key_BGN": "保加利亚列弗",
  "key_BHD": "巴林第纳尔",
  "key_BIF": "布隆迪法郎",
  "key_BMD": "百慕大美元",
  "key_BND": "文莱元",
  "key_BOB": "玻利维亚诺",
  "key_BRL": "巴西雷亚尔",
  "key_BSD": "巴哈马元",
  "key_BTC": "比特币",
  "key_BTN": "不丹努尔特鲁姆",
  "key_BWP": "博茨瓦纳普拉",
  "key_BYN": "新的白俄罗斯卢布",
  "key_BYR": "白俄罗斯卢布",
  "key_BZD": "伯利兹元",
  "key_CAD": "加拿大元",
  "key_CDF": "刚果法郎",
  "key_CHF": "瑞士法郎",
  "key_CLF": "账户智利单位（UF）",
  "key_CLP": "智利比索",
  "key_CNY": "中国元",
  "key_COP": "哥伦比亚比索",
  "key_CRC": "哥斯达黎加科隆",
  "key_CUC": "古巴可兑换比索",
  "key_CUP": "古巴比索",
  "key_CVE": "佛得角埃斯库多",
  "key_CZK": "捷克共和国克朗",
  "key_DJF": "吉布提法郎",
  "key_DKK": "丹麦克朗",
  "key_DOP": "多明尼加比索",
  "key_DZD": "阿尔及利亚第纳尔",
  "key_EGP": "埃及镑",
  "key_ERN": "厄立特里亚纳克法",
  "key_ETB": "埃塞俄比亚比尔",
  "key_EUR": "欧元",
  "key_FJD": "斐济元",
  "key_FKP": "福克兰镑",
  "key_GBP": "英镑",
  "key_GEL": "格鲁吉亚拉里",
  "key_GGP": "根西岛镑",
  "key_GHS": "加纳塞地",
  "key_GIP": "直布罗陀镑",
  "key_GMD": "冈比亚达拉西",
  "key_GNF": "几内亚法郎",
  "key_GTQ": "危地马拉格查尔",
  "key_GYD": "Guyanaese美元",
  "key_HKD": "港元",
  "key_HNL": "洪都拉斯伦皮拉",
  "key_HRK": "克罗地亚库纳",
  "key_HTG": "海地古德",
  "key_HUF": "匈牙利福林",
  "key_IDR": "印尼盾",
  "key_ILS": "以色列新谢克尔",
  "key_IMP": "曼岛镑",
  "key_INR": "印度卢比",
  "key_IQD": "伊拉克第纳尔",
  "key_IRR": "伊朗里亚尔",
  "key_ISK": "冰岛克朗",
  "key_JEP": "泽西英镑",
  "key_JMD": "牙买加元",
  "key_JOD": "约旦第纳尔",
  "key_JPY": "日圆",
  "key_KES": "肯尼亚先令",
  "key_KGS": "吉尔吉斯斯坦索姆",
  "key_KHR": "柬埔寨瑞尔",
  "key_KMF": "科摩罗法郎",
  "key_KPW": "朝鲜圆",
  "key_KRW": "韩元",
  "key_KWD": "科威特第纳尔",
  "key_KYD": "开曼群岛元",
  "key_KZT": "哈萨克斯坦坚戈",
  "key_LAK": "老挝基普",
  "key_LBP": "黎巴嫩镑",
  "key_LKR": "斯里兰卡卢比",
  "key_LRD": "利比亚元",
  "key_LSL": "莱索托洛蒂",
  "key_LTL": "立陶宛立特",
  "key_LVL": "拉脱维亚拉特",
  "key_LYD": "利比亚第纳尔",
  "key_MAD": "摩洛哥迪拉姆",
  "key_MDL": "摩尔多瓦列伊",
  "key_MGA": "阿里亚里",
  "key_MKD": "马其顿代纳尔",
  "key_MMK": "缅甸缅元",
  "key_MNT": "蒙古图格里克",
  "key_MOP": "澳门元",
  "key_MRO": "毛里塔尼亚乌吉亚",
  "key_MUR": "毛里求斯卢比",
  "key_MVR": "马尔地",
  "key_MWK": "马拉维克瓦查",
  "key_MXN": "墨西哥比索",
  "key_MYR": "马来西亚林吉特",
  "key_MZN": "莫桑比克梅蒂卡尔",
  "key_NAD": "纳米比亚元",
  "key_NGN": "尼日利亚奈拉",
  "key_NIO": "尼加拉瓜科尔多瓦",
  "key_NOK": "挪威克朗",
  "key_NPR": "尼泊尔卢比",
  "key_NZD": "新西兰元",
  "key_OMR": "阿曼里亚尔",
  "key_PAB": "巴拿马波亚",
  "key_PEN": "秘鲁新索尔",
  "key_PGK": "巴布亚新几内亚基那",
  "key_PHP": "菲律宾比索",
  "key_PKR": "巴基斯坦卢比",
  "key_PLN": "波兰兹罗提",
  "key_PYG": "巴拉圭瓜拉尼",
  "key_QAR": "卡塔尔里亚尔",
  "key_RON": "罗马尼亚列伊",
  "key_RSD": "塞尔维亚第纳尔",
  "key_RUB": "俄罗斯卢布",
  "key_RWF": "卢旺达法郎",
  "key_SAR": "沙特里亚尔",
  "key_SBD": "所罗门群岛元",
  "key_SCR": "塞舌尔卢比",
  "key_SDG": "苏丹镑",
  "key_SEK": "瑞典克朗",
  "key_SGD": "新加坡元",
  "key_SHP": "圣赫勒拿镑",
  "key_SLL": "塞拉利昂利昂",
  "key_SOS": "索马里先令",
  "key_SRD": "苏里南元",
  "key_STD": "圣多美和普林西比多布拉",
  "key_SVC": "萨尔瓦多科朗",
  "key_SYP": "叙利亚镑",
  "key_SZL": "斯威士兰里兰吉尼",
  "key_THB": "泰铢",
  "key_TJS": "塔吉克斯坦索莫尼",
  "key_TMT": "土库曼斯坦马纳特",
  "key_TND": "突尼斯第纳尔",
  "key_TOP": "汤加潘加",
  "key_TRY": "土耳其里拉",
  "key_TTD": "特立尼达和多巴哥元",
  "key_TWD": "台币",
  "key_TZS": "坦桑尼亚先令",
  "key_UAH": "乌克兰格里夫尼亚",
  "key_UGX": "乌干达先令",
  "key_USD": "美国美元",
  "key_UYU": "乌拉圭比索",
  "key_UZS": "乌兹别克斯坦索姆",
  "key_VEF": "委内瑞拉强势玻利瓦尔",
  "key_VND": "越南盾",
  "key_VUV": "瓦努阿图瓦图",
  "key_WST": "萨摩亚塔拉",
  "key_XAF": "中非金融合作法郎",
  "key_XAG": "白银（盎司）",
  "key_XAU": "黄金（盎司）",
  "key_XCD": "东加勒比元",
  "key_XDR": "特别提款权",
  "key_XOF": "非洲金融共同体法郎",
  "key_XPF": "太平洋法郎",
  "key_YER": "也门里亚尔",
  "key_ZAR": "南非兰特",
  "key_ZMK": "赞比亚克瓦查（预2013）",
  "key_ZMW": "赞比亚克瓦查",
  "key_ZWL": "津巴布韦元",
  "app_description": "用这个免费应用程序换算超过180个国家的货币和金属（黄金，银及其他） 。此应用对于想用自己的货币查询价钱的旅客是必要的。\n\n功能:\n- 自动更新汇率 (可以在设置里关闭)\n- 创建您自己的货币列表\n- 同步换算货币\n- 每个国家的国旗\n- 金融统计图表-容易使用\n- 可以线下使用 (它会储存最后更新的汇率)",
  "app_tags": "计算器, 换算, 国外, 交换, 利率, 金融, 图表, 货币, 欧元, 美元, 比索, 日元, 人民币, 旅游, 观光, 度假, 镑",
  "short_description": "换算超过180个世界货币。如果您在旅行这将是个必需品。"
};
static const Map<String,dynamic> en = {
  "app_name": "Currency Convertor",
  "search_currency": "Search Currency",
  "selected_currency": "(Selected Currency)",
  "converter": "Converter",
  "favorites": "Favorites",
  "updated_date": "Updated: {}",
  "change_language": "Change the language",
  "updating": "Updating...",
  "main_screen_instructions": "Tap a currency to make it base currency. Long tap to reorder.",
  "settings": "Settings",
  "decimals": "Decimals",
  "decimals_description": "Number of decimals to display",
  "grouping_separator": "Grouping Separator",
  "grouping_separator_description": "Enable symbol used for thousands separator",
  "decimal_separator": "Decimal Separator",
  "decimal_separator_description": "Symbol used to separate the integer part from the fractional part",
  "decimal_comma": "Decimal comma",
  "decimal_point": "Decimal point",
  "currency_symbol": "Currency Symbol",
  "currency_symbol_description": "Choose where to display the currency symbol",
  "currency_symbol_start": "Start",
  "currency_symbol_end": "End",
  "date_time_format": "dd/MMM/yyyy hh:mm a",
  "key_AED": "United Arab Emirates Dirham",
  "key_AFN": "Afghan Afghani",
  "key_ALL": "Albanian Lek",
  "key_AMD": "Armenian Dram",
  "key_ANG": "Netherlands Antillean Guilder",
  "key_AOA": "Angolan Kwanza",
  "key_ARS": "Argentine Peso",
  "key_AUD": "Australian Dollar",
  "key_AWG": "Aruban Florin",
  "key_AZN": "Azerbaijani Manat",
  "key_BAM": "Bosnia-Herzegovina Convertible Mark",
  "key_BBD": "Barbadian Dollar",
  "key_BDT": "Bangladeshi Taka",
  "key_BGN": "Bulgarian Lev",
  "key_BHD": "Bahraini Dinar",
  "key_BIF": "Burundian Franc",
  "key_BMD": "Bermudan Dollar",
  "key_BND": "Brunei Dollar",
  "key_BOB": "Bolivian Boliviano",
  "key_BRL": "Brazilian Real",
  "key_BSD": "Bahamian Dollar",
  "key_BTC": "Bitcoin",
  "key_BTN": "Bhutanese Ngultrum",
  "key_BWP": "Botswanan Pula",
  "key_BYN": "New Belarusian Ruble",
  "key_BYR": "Belarusian Ruble",
  "key_BZD": "Belize Dollar",
  "key_CAD": "Canadian Dollar",
  "key_CDF": "Congolese Franc",
  "key_CHF": "Swiss Franc",
  "key_CLF": "Chilean Unit of Account (UF)",
  "key_CLP": "Chilean Peso",
  "key_CNY": "Chinese Yuan",
  "key_COP": "Colombian Peso",
  "key_CRC": "Costa Rican Colón",
  "key_CUC": "Cuban Convertible Peso",
  "key_CUP": "Cuban Peso",
  "key_CVE": "Cape Verdean Escudo",
  "key_CZK": "Czech Republic Koruna",
  "key_DJF": "Djiboutian Franc",
  "key_DKK": "Danish Krone",
  "key_DOP": "Dominican Peso",
  "key_DZD": "Algerian Dinar",
  "key_EGP": "Egyptian Pound",
  "key_ERN": "Eritrean Nakfa",
  "key_ETB": "Ethiopian Birr",
  "key_EUR": "Euro",
  "key_FJD": "Fijian Dollar",
  "key_FKP": "Falkland Islands Pound",
  "key_GBP": "British Pound Sterling",
  "key_GEL": "Georgian Lari",
  "key_GGP": "Guernsey Pound",
  "key_GHS": "Ghanaian Cedi",
  "key_GIP": "Gibraltar Pound",
  "key_GMD": "Gambian Dalasi",
  "key_GNF": "Guinean Franc",
  "key_GTQ": "Guatemalan Quetzal",
  "key_GYD": "Guyanaese Dollar",
  "key_HKD": "Hong Kong Dollar",
  "key_HNL": "Honduran Lempira",
  "key_HRK": "Croatian Kuna",
  "key_HTG": "Haitian Gourde",
  "key_HUF": "Hungarian Forint",
  "key_IDR": "Indonesian Rupiah",
  "key_ILS": "Israeli New Sheqel",
  "key_IMP": "Manx pound",
  "key_INR": "Indian Rupee",
  "key_IQD": "Iraqi Dinar",
  "key_IRR": "Iranian Rial",
  "key_ISK": "Icelandic Króna",
  "key_JEP": "Jersey Pound",
  "key_JMD": "Jamaican Dollar",
  "key_JOD": "Jordanian Dinar",
  "key_JPY": "Japanese Yen",
  "key_KES": "Kenyan Shilling",
  "key_KGS": "Kyrgystani Som",
  "key_KHR": "Cambodian Riel",
  "key_KMF": "Comorian Franc",
  "key_KPW": "North Korean Won",
  "key_KRW": "South Korean Won",
  "key_KWD": "Kuwaiti Dinar",
  "key_KYD": "Cayman Islands Dollar",
  "key_KZT": "Kazakhstani Tenge",
  "key_LAK": "Laotian Kip",
  "key_LBP": "Lebanese Pound",
  "key_LKR": "Sri Lankan Rupee",
  "key_LRD": "Liberian Dollar",
  "key_LSL": "Lesotho Loti",
  "key_LTL": "Lithuanian Litas",
  "key_LVL": "Latvian Lats",
  "key_LYD": "Libyan Dinar",
  "key_MAD": "Moroccan Dirham",
  "key_MDL": "Moldovan Leu",
  "key_MGA": "Malagasy Ariary",
  "key_MKD": "Macedonian Denar",
  "key_MMK": "Myanma Kyat",
  "key_MNT": "Mongolian Tugrik",
  "key_MOP": "Macanese Pataca",
  "key_MRO": "Mauritanian Ouguiya",
  "key_MUR": "Mauritian Rupee",
  "key_MVR": "Maldivian Rufiyaa",
  "key_MWK": "Malawian Kwacha",
  "key_MXN": "Mexican Peso",
  "key_MYR": "Malaysian Ringgit",
  "key_MZN": "Mozambican Metical",
  "key_NAD": "Namibian Dollar",
  "key_NGN": "Nigerian Naira",
  "key_NIO": "Nicaraguan Córdoba",
  "key_NOK": "Norwegian Krone",
  "key_NPR": "Nepalese Rupee",
  "key_NZD": "New Zealand Dollar",
  "key_OMR": "Omani Rial",
  "key_PAB": "Panamanian Balboa",
  "key_PEN": "Peruvian Nuevo Sol",
  "key_PGK": "Papua New Guinean Kina",
  "key_PHP": "Philippine Peso",
  "key_PKR": "Pakistani Rupee",
  "key_PLN": "Polish Zloty",
  "key_PYG": "Paraguayan Guarani",
  "key_QAR": "Qatari Rial",
  "key_RON": "Romanian Leu",
  "key_RSD": "Serbian Dinar",
  "key_RUB": "Russian Ruble",
  "key_RWF": "Rwandan Franc",
  "key_SAR": "Saudi Riyal",
  "key_SBD": "Solomon Islands Dollar",
  "key_SCR": "Seychellois Rupee",
  "key_SDG": "Sudanese Pound",
  "key_SEK": "Swedish Krona",
  "key_SGD": "Singapore Dollar",
  "key_SHP": "Saint Helena Pound",
  "key_SLL": "Sierra Leonean Leone",
  "key_SOS": "Somali Shilling",
  "key_SRD": "Surinamese Dollar",
  "key_STD": "São Tomé and Príncipe Dobra",
  "key_SVC": "Salvadoran Colón",
  "key_SYP": "Syrian Pound",
  "key_SZL": "Swazi Lilangeni",
  "key_THB": "Thai Baht",
  "key_TJS": "Tajikistani Somoni",
  "key_TMT": "Turkmenistani Manat",
  "key_TND": "Tunisian Dinar",
  "key_TOP": "Tongan Paʻanga",
  "key_TRY": "Turkish Lira",
  "key_TTD": "Trinidad and Tobago Dollar",
  "key_TWD": "New Taiwan Dollar",
  "key_TZS": "Tanzanian Shilling",
  "key_UAH": "Ukrainian Hryvnia",
  "key_UGX": "Ugandan Shilling",
  "key_USD": "United States Dollar",
  "key_UYU": "Uruguayan Peso",
  "key_UZS": "Uzbekistan Som",
  "key_VEF": "Venezuelan Bolívar Fuerte",
  "key_VND": "Vietnamese Dong",
  "key_VUV": "Vanuatu Vatu",
  "key_WST": "Samoan Tala",
  "key_XAF": "CFA Franc BEAC",
  "key_XAG": "Silver (troy ounce)",
  "key_XAU": "Gold (troy ounce)",
  "key_XCD": "East Caribbean Dollar",
  "key_XDR": "Special Drawing Rights",
  "key_XOF": "CFA Franc BCEAO",
  "key_XPF": "CFP Franc",
  "key_YER": "Yemeni Rial",
  "key_ZAR": "South African Rand",
  "key_ZMK": "Zambian Kwacha (pre-2013)",
  "key_ZMW": "Zambian Kwacha",
  "key_ZWL": "Zimbabwean Dollar",
  "app_description": "Convert over 180 world currencies and metals (Gold, Silver and more) with this free app. This app is a must have for travelers who wants to know prices in their own currency.\n\nFeatures:\n- Automatically updated exchange rates (Can be disabled in settings)\n- Create your own list of currencies\n- Converts currencies simultaneously\n- National flags for each country\n- Financial charts- Easy to use\n- Can be used offline (it stores the last updated rates)",
  "app_tags": "calculator, converter,foreign, exchange, rate, finance, charts, money, euro, dolar, peso, yen, yuan, travel, tourist, vacation, pound",
  "short_description": "Convert over 180 world currencies.This is a must have if you are traveling."
};
static const Map<String,dynamic> zh_TW = {
  "app_name": "Currency Convertor",
  "search_currency": "搜索貨幣",
  "selected_currency": "（選擇貨幣）",
  "converter": "變流器",
  "favorites": "最愛",
  "change_language": "更改語言",
  "updated_date": "更新時間：{}",
  "updating": "更新中...",
  "main_screen_instructions": "點擊貨幣，使其基礎貨幣。長按要重新排列。",
  "settings": "設置",
  "decimals": "小數點",
  "decimals_description": "小數到顯示的號碼",
  "grouping_separator": "分組分隔",
  "grouping_separator_description": "啟用用於千位分隔符",
  "decimal_separator": "小數分隔符",
  "decimal_separator_description": "符號用於將整數部分從小數部分分離",
  "decimal_comma": "小數逗號",
  "decimal_point": "小數點",
  "currency_symbol": "貨幣符號",
  "currency_symbol_description": "選擇在哪裡顯示貨幣符號",
  "currency_symbol_start": "開始",
  "currency_symbol_end": "結束",
  "date_time_format": "yyyy年M月d日 k:mm",
  "key_AED": "阿聯酋迪拉姆",
  "key_AFN": "阿富汗阿富汗尼",
  "key_ALL": "阿爾巴尼亞列克",
  "key_AMD": "亞美尼亞德拉姆",
  "key_ANG": "荷蘭Antillian荷蘭盾",
  "key_AOA": "安哥拉寬扎",
  "key_ARS": "阿根廷比索",
  "key_AUD": "澳大利亞元",
  "key_AWG": "貨幣編號",
  "key_AZN": "阿塞拜疆馬納特",
  "key_BAM": "波斯尼亞和黑塞哥維那可兌換馬克",
  "key_BBD": "巴巴多斯元",
  "key_BDT": "孟加拉塔卡",
  "key_BGN": "保加利亞列弗",
  "key_BHD": "巴林第納爾",
  "key_BIF": "布隆迪法郎",
  "key_BMD": "百慕大美元",
  "key_BND": "文萊元",
  "key_BOB": "玻利維亞諾",
  "key_BRL": "巴西雷亞爾",
  "key_BSD": "巴哈馬元",
  "key_BTC": "比特幣",
  "key_BTN": "不丹努爾特魯姆",
  "key_BWP": "博茨瓦納普拉",
  "key_BYN": "新的白俄羅斯盧布",
  "key_BYR": "白俄羅斯盧布",
  "key_BZD": "伯利茲元",
  "key_CAD": "加拿大元",
  "key_CDF": "剛果法郎",
  "key_CHF": "瑞士法郎",
  "key_CLF": "賬戶智利單位（UF）",
  "key_CLP": "智利比索",
  "key_CNY": "中國元",
  "key_COP": "哥倫比亞比索",
  "key_CRC": "哥斯達黎加科隆",
  "key_CUC": "古巴可兌換比索",
  "key_CUP": "古巴比索",
  "key_CVE": "佛得角埃斯庫多",
  "key_CZK": "捷克共和國克朗",
  "key_DJF": "吉布提法郎",
  "key_DKK": "丹麥克朗",
  "key_DOP": "多明尼加比索",
  "key_DZD": "阿爾及利亞第納爾",
  "key_EGP": "埃及鎊",
  "key_ERN": "厄立特里亞納克法",
  "key_ETB": "埃塞俄比亞比爾",
  "key_EUR": "歐元",
  "key_FJD": "斐濟元",
  "key_FKP": "福克蘭鎊",
  "key_GBP": "英鎊",
  "key_GEL": "格魯吉亞拉里",
  "key_GGP": "根西島鎊",
  "key_GHS": "加納塞地",
  "key_GIP": "直布羅陀鎊",
  "key_GMD": "岡比亞達拉西",
  "key_GNF": "幾內亞法郎",
  "key_GTQ": "危地馬拉格查爾",
  "key_GYD": "Guyanaese美元",
  "key_HKD": "港元",
  "key_HNL": "洪都拉斯倫皮拉",
  "key_HRK": "克羅地亞庫納",
  "key_HTG": "海地古德",
  "key_HUF": "匈牙利福林",
  "key_IDR": "印尼盾",
  "key_ILS": "以色列新謝克爾",
  "key_IMP": "曼島鎊",
  "key_INR": "印度盧比",
  "key_IQD": "伊拉克第納爾",
  "key_IRR": "伊朗里亞爾",
  "key_ISK": "冰島克朗",
  "key_JEP": "澤西英鎊",
  "key_JMD": "牙買加元",
  "key_JOD": "約旦第納爾",
  "key_JPY": "日圓",
  "key_KES": "肯尼亞先令",
  "key_KGS": "吉爾吉斯斯坦索姆",
  "key_KHR": "柬埔寨瑞爾",
  "key_KMF": "科摩羅法郎",
  "key_KPW": "朝鮮圓",
  "key_KRW": "韓元",
  "key_KWD": "科威特第納爾",
  "key_KYD": "開曼群島元",
  "key_KZT": "哈薩克斯坦堅戈",
  "key_LAK": "老撾基普",
  "key_LBP": "黎巴嫩鎊",
  "key_LKR": "斯里蘭卡盧比",
  "key_LRD": "利比亞元",
  "key_LSL": "萊索托洛蒂",
  "key_LTL": "立陶宛立特",
  "key_LVL": "拉脫維亞拉特",
  "key_LYD": "利比亞第納爾",
  "key_MAD": "摩洛哥迪拉姆",
  "key_MDL": "摩爾多瓦列伊",
  "key_MGA": "阿里亞裡",
  "key_MKD": "馬其頓代納爾",
  "key_MMK": "緬甸緬元",
  "key_MNT": "蒙古圖格里克",
  "key_MOP": "澳門元",
  "key_MRO": "毛里塔尼亞烏吉亞",
  "key_MUR": "毛里求斯盧比",
  "key_MVR": "馬爾地",
  "key_MWK": "馬拉維克瓦查",
  "key_MXN": "墨西哥比索",
  "key_MYR": "馬來西亞林吉特",
  "key_MZN": "莫桑比克梅蒂卡爾",
  "key_NAD": "納米比亞元",
  "key_NGN": "尼日利亞奈拉",
  "key_NIO": "尼加拉瓜科爾多瓦",
  "key_NOK": "挪威克朗",
  "key_NPR": "尼泊爾盧比",
  "key_NZD": "新西蘭元",
  "key_OMR": "阿曼里亞爾",
  "key_PAB": "巴拿馬波亞",
  "key_PEN": "秘魯新索爾",
  "key_PGK": "巴布亞新幾內亞基那",
  "key_PHP": "菲律賓比索",
  "key_PKR": "巴基斯坦盧比",
  "key_PLN": "波蘭茲羅提",
  "key_PYG": "巴拉圭瓜拉尼",
  "key_QAR": "卡塔爾里亞爾",
  "key_RON": "羅馬尼亞列伊",
  "key_RSD": "塞爾維亞第納爾",
  "key_RUB": "俄羅斯盧布",
  "key_RWF": "盧旺達法郎",
  "key_SAR": "沙特里亞爾",
  "key_SBD": "所羅門群島元",
  "key_SCR": "塞舌爾盧比",
  "key_SDG": "蘇丹鎊",
  "key_SEK": "瑞典克朗",
  "key_SGD": "新加坡元",
  "key_SHP": "聖赫勒拿鎊",
  "key_SLL": "塞拉利昂利昂",
  "key_SOS": "索馬里先令",
  "key_SRD": "蘇里南元",
  "key_STD": "聖多美和普林西比多布拉",
  "key_SVC": "薩爾瓦多科朗",
  "key_SYP": "敘利亞鎊",
  "key_SZL": "斯威士蘭里蘭吉尼",
  "key_THB": "泰銖",
  "key_TJS": "塔吉克斯坦索莫尼",
  "key_TMT": "土庫曼斯坦馬納特",
  "key_TND": "突尼斯第納爾",
  "key_TOP": "湯加潘加",
  "key_TRY": "土耳其里拉",
  "key_TTD": "特立尼達和多巴哥元",
  "key_TWD": "台幣",
  "key_TZS": "坦桑尼亞先令",
  "key_UAH": "烏克蘭格里夫尼亞",
  "key_UGX": "烏干達先令",
  "key_USD": "美國美元",
  "key_UYU": "烏拉圭比索",
  "key_UZS": "烏茲別克斯坦索姆",
  "key_VEF": "委內瑞拉強勢玻利瓦爾",
  "key_VND": "越南盾",
  "key_VUV": "瓦努阿圖瓦圖",
  "key_WST": "薩摩亞塔拉",
  "key_XAF": "中非金融合作法郎",
  "key_XAG": "白銀（盎司）",
  "key_XAU": "黃金（盎司）",
  "key_XCD": "東加勒比元",
  "key_XDR": "特別提款權",
  "key_XOF": "非洲金融共同體法郎",
  "key_XPF": "太平洋法郎",
  "key_YER": "也門里亞爾",
  "key_ZAR": "南非蘭特",
  "key_ZMK": "贊比亞克瓦查（預2013）",
  "key_ZMW": "贊比亞克瓦查",
  "key_ZWL": "津巴布韋元",
  "app_description": "用這個免費應用程序換算超過180個國家的貨幣和金屬（黃金，銀及其他） 。此應用對於想用自己的貨幣查詢價錢的旅客是必要的。 \n\n功能:\n- 自動更新匯率(可以在設置里關閉)\n- 創建您自己的貨幣列表\n- 同步換算貨幣\n- 每個國家的國旗\n- 金融統計圖表-容易使用\n- 可以線下使用(它會儲存最後更新的匯率)",
  "app_tags": "計算器, 換算, 國外, 交換, 利率, 金融, 圖表, 貨幣, 歐元, 美元, 比索, 日元, 人民幣, 旅遊, 觀光, 度假, 鎊",
  "short_description": "換算超過180個世界貨幣。如果您在旅行這將是個必需品。"
};
static const Map<String,dynamic> es = {
  "app_name": "Currency Convertor",
  "search_currency": "Búsqueda de divisas",
  "selected_currency": "(Divisa seleccionada)",
  "converter": "Convertidor",
  "favorites": "Favoritos",
  "change_language": "Cambiar idioma",
  "updated_date": "Actualizado: {}",
  "updating": "Actualizando...",
  "main_screen_instructions": "Toque una moneda para que sea la divisa base. Presiona por mas tiempo para ordenar.",
  "settings": "Ajustes",
  "decimals": "Decimales",
  "decimals_description": "Número de decimales que se visualizarán",
  "grouping_separator": "Separador de agrupación",
  "grouping_separator_description": "Habilitar el símbolo utilizado para el separador de miles",
  "decimal_separator": "Separador decimal",
  "decimal_separator_description": "Símbolo utilizado para separar la parte entera de la parte fraccional",
  "decimal_comma": "coma decimal",
  "decimal_point": "Punto decimal",
  "currency_symbol": "Simbolo de la divisa",
  "currency_symbol_description": "Donde deseas mostrar el simbolo de la divisa",
  "currency_symbol_start": "Inicio",
  "currency_symbol_end": "Final",
  "date_time_format": "dd/MMM/yyyy hh:mm a",
  "key_AED": "Emiratos Árabes Unidos Dirham",
  "key_AFN": "Afghanistan Afghani",
  "key_ALL": "Lek albanés",
  "key_AMD": "armenia Dram",
  "key_ANG": "Florín antillano",
  "key_AOA": "Kwanza angoleño",
  "key_ARS": "Peso argentino",
  "key_AUD": "Dólar australiano",
  "key_AWG": "florines",
  "key_AZN": "Azerbaiyán manat",
  "key_BAM": "Bosnia-Herzegovina convertible marca",
  "key_BBD": "Dólar de Barbados",
  "key_BDT": "Bangladesh Taka",
  "key_BGN": "Lev Bulgaria",
  "key_BHD": "Dinar de Bahrein",
  "key_BIF": "Burundi Franc",
  "key_BMD": "Dólar de bermudas",
  "key_BND": "Dólar de Brunei",
  "key_BOB": "boliviano",
  "key_BRL": "Real brasileño",
  "key_BSD": "Dólar de las Bahamas",
  "key_BTC": "Bitcoin",
  "key_BTN": "Ngultrum Bhután",
  "key_BWP": "pula de Botsuana",
  "key_BYN": "Rublo bielorruso nueva",
  "key_BYR": "Rublo bielorruso",
  "key_BZD": "Dólar de Belice",
  "key_CAD": "Dolar canadiense",
  "key_CDF": "Franco congoleño",
  "key_CHF": "Franco suizo",
  "key_CLF": "Unidad chilena de la cuenta (UF)",
  "key_CLP": "Peso chileno",
  "key_CNY": "Yuan chino",
  "key_COP": "Peso colombiano",
  "key_CRC": "Costa Rica Colón",
  "key_CUC": "Peso Cubano Convertible",
  "key_CUP": "Peso cubano",
  "key_CVE": "Cabo Verde escudo",
  "key_CZK": "Corona checa",
  "key_DJF": "franco de Yibuti",
  "key_DKK": "danesa",
  "key_DOP": "Peso dominicano",
  "key_DZD": "Dinar argelino",
  "key_EGP": "Libra egipcia",
  "key_ERN": "Eritrea Nakfa",
  "key_ETB": "Birr etíope",
  "key_EUR": "Euro",
  "key_FJD": "Dólar fiyiano",
  "key_FKP": "Libra de las Islas Malvinas",
  "key_GBP": "Libra esterlina británica",
  "key_GEL": "Lari georgiano",
  "key_GGP": "Libra de Guernsey",
  "key_GHS": "Cedi de Ghana",
  "key_GIP": "Libra de Gibraltar",
  "key_GMD": "Dalasi de Gambia",
  "key_GNF": "Franco guineano",
  "key_GTQ": "Quetzal de Guatemala",
  "key_GYD": "Guyanaese dólar",
  "key_HKD": "Dolar de Hong Kong",
  "key_HNL": "Lempira hondureña",
  "key_HRK": "Kuna croata",
  "key_HTG": "Gourde haitiano",
  "key_HUF": "Florín húngaro",
  "key_IDR": "Rupia Indonesia",
  "key_ILS": "Shekel israelí Nuevo",
  "key_IMP": "Manx libras",
  "key_INR": "Rupia india",
  "key_IQD": "Dinar iraquí",
  "key_IRR": "Rial iraní",
  "key_ISK": "corona islandesa",
  "key_JEP": "Libra de Jersey",
  "key_JMD": "Dólar de Jamaica",
  "key_JOD": "Dinar jordano",
  "key_JPY": "Yen japonés",
  "key_KES": "Chelín de Kenia",
  "key_KGS": "Kyrgystani Som",
  "key_KHR": "Riel camboyano",
  "key_KMF": "franco comorano",
  "key_KPW": "Corea del Norte ganó",
  "key_KRW": "Corea del Sur ganó",
  "key_KWD": "Dinar kuwaití",
  "key_KYD": "Islas Cayman Dólar",
  "key_KZT": "tenge kazako",
  "key_LAK": "Laos Kip",
  "key_LBP": "Libra libanesa",
  "key_LKR": "Rupia de Sri Lanka",
  "key_LRD": "Dólar liberiano",
  "key_LSL": "Lesotho Loti",
  "key_LTL": "Litas lituana",
  "key_LVL": "lats",
  "key_LYD": "Dinar libio",
  "key_MAD": "Dirham de marruecos",
  "key_MDL": "Leu moldavo",
  "key_MGA": "Ariary malgache",
  "key_MKD": "Denar macedonio",
  "key_MMK": "Myanmar kyats",
  "key_MNT": "Mongolia Tugrik",
  "key_MOP": "Pataca de Macao",
  "key_MRO": "uquiya",
  "key_MUR": "Rupia de Mauricio",
  "key_MVR": "Rupia de Maldivas",
  "key_MWK": "kwacha de Malawi",
  "key_MXN": "Peso Mexicano",
  "key_MYR": "Ringgit malayo",
  "key_MZN": "Mozambique Metical",
  "key_NAD": "Dólar namibio",
  "key_NGN": "Naira Nigeria",
  "key_NIO": "Nicaragua Córdoba",
  "key_NOK": "Corona noruega",
  "key_NPR": "Rupia de Nepal",
  "key_NZD": "Dolar de Nueva Zelanda",
  "key_OMR": "Rial omaní",
  "key_PAB": "Balboa panameño",
  "key_PEN": "Nuevo Sol peruano",
  "key_PGK": "Papua Nueva Guinea Kina",
  "key_PHP": "Peso filipino",
  "key_PKR": "Rupia paquistaní",
  "key_PLN": "Zloty polaco",
  "key_PYG": "guaraní paraguayo",
  "key_QAR": "Rial qatarí",
  "key_RON": "Leu rumano",
  "key_RSD": "Dinar serbio",
  "key_RUB": "Rublo ruso",
  "key_RWF": "Ruanda Franco",
  "key_SAR": "Riyal saudí",
  "key_SBD": "Islas Salomón Dólar",
  "key_SCR": "Rupia de Seychelles",
  "key_SDG": "Libra sudanesa",
  "key_SEK": "Corona sueca",
  "key_SGD": "Dolar de Singapur",
  "key_SHP": "Santa Helena Libra",
  "key_SLL": "Sierra Leona Leona",
  "key_SOS": "Chelín somalí",
  "key_SRD": "Dólar de Suriname",
  "key_STD": "Santo Tomé y Príncipe dobra",
  "key_SVC": "Colón salvadoreño",
  "key_SYP": "Libra Siria",
  "key_SZL": "Swazilandia Lilangeni",
  "key_THB": "baht tailandés",
  "key_TJS": "tajikistani Somoni",
  "key_TMT": "Manat turkmeno",
  "key_TND": "Dinar tunecino",
  "key_TOP": "Pa'anga",
  "key_TRY": "Lira turca",
  "key_TTD": "Trinidad y Tobago Dólar",
  "key_TWD": "Nuevo dólar de Taiwán",
  "key_TZS": "Shilling tanzano",
  "key_UAH": "Hryvnia Ucrania",
  "key_UGX": "Shilling de Uganda",
  "key_USD": "Dólar de los Estados Unidos",
  "key_UYU": "Peso uruguayo",
  "key_UZS": "Uzbekistán som",
  "key_VEF": "Venezuela Bolívar Fuerte",
  "key_VND": "Dong vietnamita",
  "key_VUV": "Vanuatu Vatu",
  "key_WST": "Samoan Tala",
  "key_XAF": "Franco CFA BEAC",
  "key_XAG": "Silver (oz troy)",
  "key_XAU": "Oro (onza)",
  "key_XCD": "Dólar del Caribe Oriental",
  "key_XDR": "Derechos especiales de dibujo",
  "key_XOF": "Franco CFA BCEAO",
  "key_XPF": "Franco CFP",
  "key_YER": "Rial yemení",
  "key_ZAR": "Rand sudafricano",
  "key_ZMK": "Kwacha zambiano (pre-2013)",
  "key_ZMW": "Kwacha zambiano",
  "key_ZWL": "Zimbabwe Dólar",
  "app_description": "Convierte mas de 180 monedas y metales (Oro, Plata y mas) con esta app gratuita. Esta app es indispensable para los viajeros que quieran saber los precios en su propia moneda.\n\nCaracteristicas:\n- Tipo de cambio actualizado automaticamente (Se puede deshabilitar en ajustes)\n- Crea tu propia lista de monedas\n- Convierte varias monedas al mismo tiempo\n- Banderas nacionales para cada pais\n- Estadisticas financieras\n- Facil de usar\n- Puede ser utilizada sin conexion (Guarda los ultimos tipo de cambio descargados)",
  "app_tags": "calculadora, convertidor, extranjero, intercambio, tipo, finanzas, estadisticas, dinero, euro, dolar, peso, yen, yuan, viajar, turista, vacaciones, libra",
  "short_description": "Convierte mas de 180 monedas. Esta aplicación es indispensable para viajeros"
};
static const Map<String, Map<String,dynamic>> mapLocales = {"zh_CN": zh_CN, "en": en, "zh_TW": zh_TW, "es": es};
}
