name: flutter_simple_rest_api_getx
description: Learn flutter. Http, Getx, Sqflite, UnitTest
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  get_it: ^8.0.3
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  http: ^1.3.0
  shimmer: ^3.0.0
  sqflite: ^2.4.2
  cached_network_image: ^3.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mockito: ^5.4.5
  build_runner: ^2.4.15
  bloc_test: ^10.0.0

flutter:

  uses-material-design: true