name: flutter_simple_rest_api_getx
description: Learn flutter. Http, Getx, Sqflite, UnitTest
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  get_it: ^7.6.0
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  http: ^0.13.6
  shimmer: ^2.0.0
  sqflite: ^2.2.8+2
  cached_network_image: ^3.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  mockito: ^5.4.0
  build_runner: ^2.4.4
  bloc_test: ^9.1.1

flutter:

  uses-material-design: true